name: Awesome readme lint double link action
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: awesome readme lint double link
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Scrum/awesome-readme-lint-double-link-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
